#!/bin/bash

# Save the old HOME so we can reset after script.
# Bower and bower as it is run buy grunt both want
# to touch .local and .config files in $HOME which 
# isn't writeable on OSE.  So we set $HOME to 
# the REPO_DIR temporarily.

OLD_HOME=$HOME; cd $OPENSHIFT_REPO_DIR; HOME=$OPENSHIFT_REPO_DIR; grunt build; HOME=$OLD_HOME; cd ~; gear restart;
